language: node_js
node_js:
  - 0.8
rvm:
  - 1.8.7


before_install:
  - gem install sass
  - npm install -g grunt-cli
  - git clone git://github.com/n1k0/casperjs.git ~/casperjs
  - cd ~/casperjs
  - git checkout tags/1.0.2
  - export PATH=$PATH:`pwd`/bin
  - cd -

before_script:
  - phantomjs --version
  - casperjs --version
  - ruby --version
  - sass --version

# Intern installation
# https://github.com/theintern/intern/wiki/Travis-CI-integration
install:
  - npm install
  - cd node_modules/intern
  - npm install --production
  - cd ../..

# Test the code
script:
  - npm test
  # please get your own free key if you want to test yourself
  - SAUCE_USERNAME=ariaMenu SAUCE_ACCESS_KEY=ecd461a4-d549-409e-a7da-40533e8fba93 node node_modules/intern/runner.js config=tests/sauceLabs/intern.config.js
